### ISSUE TITLE
 JSON fetch error: Invalid JSON payload received. Unknown name "extract_entity_sentiment" at 'features': Cannot find field.

### ISSUE THREAD

**Issue by spacecrusader** [MarkEdmondson1234/googleLanguageR#1]
R 3.4
Installed googleLanguageR via devtools today.

Running the basic sample query to Natural Language API from your code results in error.

`text <- "to administer medicince to animals is frequently a very difficult matter, and yet sometimes it's necessary to do so"`
`nlp_result <- gl_nlp(text)`

Error:
`2017-05-04 12:25:40 -- annotateTextanalyzeEntitiesanalyzeSentimentanalyzeSyntaxanalyzeEntitySentiment for 'to administer medicince to animals is frequently a very difficult matter, and yet sometimes it's nec...'
Request Status Code: 400
Error in checkGoogleAPIError(req) : 
  JSON fetch error: Invalid JSON payload received. Unknown name "extract_entity_sentiment" at 'features': Cannot find field.`

Thoughts?

**Comment by MarkEdmondson1234** [comment]
Thanks for the report @spacecrusader !  I missed out the API version, from now (reinstall from github) you can also pass the API version "v1beta2" to get the new features announced.

**Comment by MarkEdmondson1234** [comment]
Sorry you downloaded it between a release and a test, so it was broken, but now it works.

**Comment by spacecrusader** [comment]
Super. I re-installed and it works. Thanks!
